[build]
command = "npm run build"
publish = "public/"
base = ""

[build.environment]
NETLIFY_IMAGE_CDN = "true"

[images]
remote_images = [
  "https://images.unsplash.com/.*",
  "https://www.gatsbyjs.com/.*",
]
